name: React App CI/CD with Rollback

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: CI=false npm run build --if-present

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            APP_DIR="/var/www/html/my-react-app"
            BACKUP_DIR="/var/www/html/my-react-app-backup"

            echo "Creating backup of current version..."
            rm -rf $BACKUP_DIR
            cp -r $APP_DIR $BACKUP_DIR

            echo "Deploying new build..."
            rm -rf $APP_DIR/build
            mkdir -p $APP_DIR
            exit
          EOF

      - name: Copy new build files
        run: |
          scp -o StrictHostKeyChecking=no -r build/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/html/my-react-app/

      - name: Verify deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            if [ ! -d "/var/www/html/my-react-app/build" ]; then
              echo "Build folder missing! Rolling back..."
              rm -rf /var/www/html/my-react-app
              mv /var/www/html/my-react-app-backup /var/www/html/my-react-app
              exit 1
            fi
            echo "Deployment successful!"
          EOF
