name: Deploy React App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            echo "📦 Starting deployment on server"

            # Define paths
            APP_DIR=/var/www/myapp
            BACKUP_DIR=/var/www/backups/myapp_$(date +%Y%m%d%H%M%S)

            # Step 1: Backup current build
            if [ -d "$APP_DIR/build" ]; then
              echo "📂 Backing up current build"
              mkdir -p /var/www/backups
              mv $APP_DIR/build $BACKUP_DIR
            fi

            # Step 2: Pull latest code
            cd $APP_DIR
            git fetch --all
            git reset --hard origin/main

            # Step 3: Install deps & build
            echo "⚙️ Running npm install & build"
            npm install
            if npm run build; then
              echo "✅ Build succeeded"
            else
              echo "❌ Build failed, rolling back..."
              rm -rf $APP_DIR/build
              mv $BACKUP_DIR $APP_DIR/build
              exit 1
            fi

            echo "🚀 Deployment completed successfully!"
