name: React App CI/CD with Rollback

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: CI=false npm run build --if-present

      # 🔑 Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            APP_DIR="/var/www/html/my-react-app"
            BACKUP_DIR="/var/www/html/my-react-app-backup"

            echo "Creating backup of current version..."
            rm -rf $BACKUP_DIR
            cp -r $APP_DIR $BACKUP_DIR || true

            echo "Deploying new build..."
            rm -rf $APP_DIR/build
            mkdir -
