name: Build & Deploy React (atomic + automatic rollback)

on:
  push:
    branches: [ "main" ]   # or the branch you want to trigger on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Archive build
        run: |
          tar -czf build.tar.gz -C build .

      - name: Copy build to server (scp)
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}            # optional, leave blank if not using
          source: "build.tar.gz"
          target: "/tmp/${{ github.run_id }}"      # puts tar under a unique temporary folder

      - name: Run remote deploy script (executes scripts/remote_deploy.sh on server)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_path: scripts/remote_deploy.sh
          envs: TAR_PATH,APP_ROOT,KEEP_RELEASES
        env:
          TAR_PATH: "/tmp/${{ github.run_id }}/build.tar.gz"
          APP_ROOT: "/var/www/html/my-react-app"
          KEEP_RELEASES: "5"
